print ("Please enter a character for the eye ")
var = input()
print ("Beep's expression is now as follows:")
print ("##########")
print ("#  " + var + "  " + var +"  #")
print ("#  ----  #")
print ("##########")