print("Please enter the number of lives.")
lives = input()
print()
print("Please enter the energy level.")
energy = input()
print()
print("Please enter the shield level.")
shield = input()
print()
print("Health has been set.")
print()
print("Lives: " + ('♥' * int(lives)))
print("Energy: " + ('♦' * int(energy)))
print("Shield: " + ('♦' * int(shield)))